site_name: Alna
site_url: https://docs.alna.com.br

nav:
  - Início: index.md
  - Guia de Documentação:
      - 'Geral': 'guideline/general.md'
      - 'Abas': 'guideline/tabs.md'
      - 'Admoestação': 'guideline/admonition.md'
      - 'Código': 'guideline/code.md'
      - 'Diagramas': 'guideline/diagram.md'

# Define theme and appearance.
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
#  font:
#    text: Merriweather Sans
#    code: Red Hat Mono
  palette:
    # Dark Mode.
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: green
      accent: deep purple

    # Light Mode.
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue
      accent: deep oragen

# Add extension to use emoji.
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
